PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE links (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hashURL TEXT NOT NULL,
    longURL TEXT NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    key_id INTEGER,
    FOREIGN KEY (key_id) REFERENCES keys(id) ON DELETE CASCADE
);

CREATE TABLE keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    apiKey TEXT NOT NULL UNIQUE,
    expiresAt TIMESTAMP NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

END TRANSACTION;
