name: hourly-maintenance

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # manual run

jobs:
  rmv-expired-keys-and-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: scripts
        run: pip install -r requirements.txt

      - name: Run Python script
        working-directory: scripts
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          LOCAL_DB_PATH: ${{ secrets.LOCAL_DB_PATH }}
        run: python ./maintenance.py
